apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: simple-nodejs-app-hgad
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-iucw-tenant/nodejs-users/simple-nodejs-app-hgad@sha256:38cb053fe8a4b7f78ac874542683b8c64bc15b0d6d75261ba0c4d4a43d0049fb
        name: my-nodejs
        resources: {}
status: {}
